dir: '{{.InterfaceDirRelative}}'
template: testify
template-data:
  mock-build-tags: '!release'
  unroll-variadic: true

# By default all mocks are written to same file
# We don't want that. AI may have hard time to read large file.
filename: "mock_{{snakecase .InterfaceName}}_test.go"

packages:
  log/slog:
    interfaces:
      Handler:
        config:
          pkgname: telemetry
          structname: '{{.Mock}}Slog{{.InterfaceName}}'
          filename: "mock_slog_{{snakecase .InterfaceName}}_test.go"
          dir: 'internal/telemetry'
  github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1controllers:
    interfaces:
      UserCommands:
      UserQueries:
      PetsCommands:
      PetsQueries:
  github.com/gemyago/golang-backend-boilerplate/internal/app:
    interfaces:
      UsersRepository:
      PetsRepository:
      PetstoreClient:
