# go-test-coverage tool is used to check for coverage threshold (see https://github.com/vladopajic/go-test-coverage)

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  # (optional; default 0) 
  # The minimum coverage that each file should have
  file: 90

  # (optional; default 0) 
  # The minimum coverage that each package should have
  # package: 0

  # (optional; default 0) 
  # The minimum total coverage project should have
  total: 90

# Holds regexp rules which will exclude matched files or packages
# from coverage statistics
exclude:
  # Exclude files or packages matching their paths
  paths:
    - testing.go
    - mock_.*.go
    - mock_*.go
    - mock.go
    - register.go # Dependency injection setup
    - internal/api/http/v1routes/.* # Generated code
    - internal/app/models/.* # Generated code
    - internal/api/http/v1controllers/pets.go # Stub implementation