// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package v1controllers

import (
	"context"

	"github.com/gemyago/golang-backend-boilerplate/internal/infrastructure/petstore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPetsQueries creates a new instance of MockPetsQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetsQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetsQueries {
	mock := &MockPetsQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPetsQueries is an autogenerated mock type for the PetsQueries type
type MockPetsQueries struct {
	mock.Mock
}

type MockPetsQueries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetsQueries) EXPECT() *MockPetsQueries_Expecter {
	return &MockPetsQueries_Expecter{mock: &_m.Mock}
}

// ListUserPets provides a mock function for the type MockPetsQueries
func (_mock *MockPetsQueries) ListUserPets(ctx context.Context, userID string) ([]*petstore.Pet, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserPets")
	}

	var r0 []*petstore.Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*petstore.Pet, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*petstore.Pet); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*petstore.Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetsQueries_ListUserPets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserPets'
type MockPetsQueries_ListUserPets_Call struct {
	*mock.Call
}

// ListUserPets is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPetsQueries_Expecter) ListUserPets(ctx interface{}, userID interface{}) *MockPetsQueries_ListUserPets_Call {
	return &MockPetsQueries_ListUserPets_Call{Call: _e.mock.On("ListUserPets", ctx, userID)}
}

func (_c *MockPetsQueries_ListUserPets_Call) Run(run func(ctx context.Context, userID string)) *MockPetsQueries_ListUserPets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetsQueries_ListUserPets_Call) Return(pets []*petstore.Pet, err error) *MockPetsQueries_ListUserPets_Call {
	_c.Call.Return(pets, err)
	return _c
}

func (_c *MockPetsQueries_ListUserPets_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*petstore.Pet, error)) *MockPetsQueries_ListUserPets_Call {
	_c.Call.Return(run)
	return _c
}
