// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package v1controllers

import (
	"context"

	"github.com/gemyago/golang-backend-boilerplate/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPetsCommands creates a new instance of MockPetsCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetsCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetsCommands {
	mock := &MockPetsCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPetsCommands is an autogenerated mock type for the PetsCommands type
type MockPetsCommands struct {
	mock.Mock
}

type MockPetsCommands_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetsCommands) EXPECT() *MockPetsCommands_Expecter {
	return &MockPetsCommands_Expecter{mock: &_m.Mock}
}

// AddPet provides a mock function for the type MockPetsCommands
func (_mock *MockPetsCommands) AddPet(ctx context.Context, req app.AddPetRequest) (*app.AddPetResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddPet")
	}

	var r0 *app.AddPetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.AddPetRequest) (*app.AddPetResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.AddPetRequest) *app.AddPetResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.AddPetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.AddPetRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetsCommands_AddPet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPet'
type MockPetsCommands_AddPet_Call struct {
	*mock.Call
}

// AddPet is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.AddPetRequest
func (_e *MockPetsCommands_Expecter) AddPet(ctx interface{}, req interface{}) *MockPetsCommands_AddPet_Call {
	return &MockPetsCommands_AddPet_Call{Call: _e.mock.On("AddPet", ctx, req)}
}

func (_c *MockPetsCommands_AddPet_Call) Run(run func(ctx context.Context, req app.AddPetRequest)) *MockPetsCommands_AddPet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.AddPetRequest
		if args[1] != nil {
			arg1 = args[1].(app.AddPetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetsCommands_AddPet_Call) Return(addPetResponse *app.AddPetResponse, err error) *MockPetsCommands_AddPet_Call {
	_c.Call.Return(addPetResponse, err)
	return _c
}

func (_c *MockPetsCommands_AddPet_Call) RunAndReturn(run func(ctx context.Context, req app.AddPetRequest) (*app.AddPetResponse, error)) *MockPetsCommands_AddPet_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePet provides a mock function for the type MockPetsCommands
func (_mock *MockPetsCommands) RemovePet(ctx context.Context, userID string, petID int64) error {
	ret := _mock.Called(ctx, userID, petID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, userID, petID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPetsCommands_RemovePet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePet'
type MockPetsCommands_RemovePet_Call struct {
	*mock.Call
}

// RemovePet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - petID int64
func (_e *MockPetsCommands_Expecter) RemovePet(ctx interface{}, userID interface{}, petID interface{}) *MockPetsCommands_RemovePet_Call {
	return &MockPetsCommands_RemovePet_Call{Call: _e.mock.On("RemovePet", ctx, userID, petID)}
}

func (_c *MockPetsCommands_RemovePet_Call) Run(run func(ctx context.Context, userID string, petID int64)) *MockPetsCommands_RemovePet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPetsCommands_RemovePet_Call) Return(err error) *MockPetsCommands_RemovePet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPetsCommands_RemovePet_Call) RunAndReturn(run func(ctx context.Context, userID string, petID int64) error) *MockPetsCommands_RemovePet_Call {
	_c.Call.Return(run)
	return _c
}
