// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package v1controllers

import (
	"context"

	"github.com/gemyago/golang-backend-boilerplate/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserQueries creates a new instance of MockUserQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserQueries {
	mock := &MockUserQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserQueries is an autogenerated mock type for the UserQueries type
type MockUserQueries struct {
	mock.Mock
}

type MockUserQueries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserQueries) EXPECT() *MockUserQueries_Expecter {
	return &MockUserQueries_Expecter{mock: &_m.Mock}
}

// GetUserByID provides a mock function for the type MockUserQueries
func (_mock *MockUserQueries) GetUserByID(ctx context.Context, userID string) (*app.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *app.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*app.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *app.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserQueries_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserQueries_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserQueries_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockUserQueries_GetUserByID_Call {
	return &MockUserQueries_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserQueries_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockUserQueries_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserQueries_GetUserByID_Call) Return(user *app.User, err error) *MockUserQueries_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserQueries_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*app.User, error)) *MockUserQueries_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockUserQueries
func (_mock *MockUserQueries) ListUsers(ctx context.Context) ([]*app.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*app.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*app.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*app.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*app.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserQueries_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserQueries_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserQueries_Expecter) ListUsers(ctx interface{}) *MockUserQueries_ListUsers_Call {
	return &MockUserQueries_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *MockUserQueries_ListUsers_Call) Run(run func(ctx context.Context)) *MockUserQueries_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserQueries_ListUsers_Call) Return(users []*app.User, err error) *MockUserQueries_ListUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserQueries_ListUsers_Call) RunAndReturn(run func(ctx context.Context) ([]*app.User, error)) *MockUserQueries_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}
