// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package v1controllers

import (
	"context"

	"github.com/gemyago/golang-backend-boilerplate/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserCommands creates a new instance of MockUserCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCommands {
	mock := &MockUserCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCommands is an autogenerated mock type for the UserCommands type
type MockUserCommands struct {
	mock.Mock
}

type MockUserCommands_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCommands) EXPECT() *MockUserCommands_Expecter {
	return &MockUserCommands_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserCommands
func (_mock *MockUserCommands) CreateUser(ctx context.Context, req app.CreateUserRequest) (*app.CreateUserResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *app.CreateUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.CreateUserRequest) (*app.CreateUserResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.CreateUserRequest) *app.CreateUserResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.CreateUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.CreateUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserCommands_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserCommands_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.CreateUserRequest
func (_e *MockUserCommands_Expecter) CreateUser(ctx interface{}, req interface{}) *MockUserCommands_CreateUser_Call {
	return &MockUserCommands_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, req)}
}

func (_c *MockUserCommands_CreateUser_Call) Run(run func(ctx context.Context, req app.CreateUserRequest)) *MockUserCommands_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.CreateUserRequest
		if args[1] != nil {
			arg1 = args[1].(app.CreateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCommands_CreateUser_Call) Return(createUserResponse *app.CreateUserResponse, err error) *MockUserCommands_CreateUser_Call {
	_c.Call.Return(createUserResponse, err)
	return _c
}

func (_c *MockUserCommands_CreateUser_Call) RunAndReturn(run func(ctx context.Context, req app.CreateUserRequest) (*app.CreateUserResponse, error)) *MockUserCommands_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserCommands
func (_mock *MockUserCommands) DeleteUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserCommands_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserCommands_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserCommands_Expecter) DeleteUser(ctx interface{}, userID interface{}) *MockUserCommands_DeleteUser_Call {
	return &MockUserCommands_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userID)}
}

func (_c *MockUserCommands_DeleteUser_Call) Run(run func(ctx context.Context, userID string)) *MockUserCommands_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCommands_DeleteUser_Call) Return(err error) *MockUserCommands_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserCommands_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockUserCommands_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserCommands
func (_mock *MockUserCommands) UpdateUser(ctx context.Context, req app.UpdateUserRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.UpdateUserRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserCommands_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserCommands_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.UpdateUserRequest
func (_e *MockUserCommands_Expecter) UpdateUser(ctx interface{}, req interface{}) *MockUserCommands_UpdateUser_Call {
	return &MockUserCommands_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, req)}
}

func (_c *MockUserCommands_UpdateUser_Call) Run(run func(ctx context.Context, req app.UpdateUserRequest)) *MockUserCommands_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.UpdateUserRequest
		if args[1] != nil {
			arg1 = args[1].(app.UpdateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCommands_UpdateUser_Call) Return(err error) *MockUserCommands_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserCommands_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, req app.UpdateUserRequest) error) *MockUserCommands_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
