// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package telemetry

import (
	"context"
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSlogHandler creates a new instance of MockSlogHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlogHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlogHandler {
	mock := &MockSlogHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlogHandler is an autogenerated mock type for the Handler type
type MockSlogHandler struct {
	mock.Mock
}

type MockSlogHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlogHandler) EXPECT() *MockSlogHandler_Expecter {
	return &MockSlogHandler_Expecter{mock: &_m.Mock}
}

// Enabled provides a mock function for the type MockSlogHandler
func (_mock *MockSlogHandler) Enabled(context1 context.Context, level slog.Level) bool {
	ret := _mock.Called(context1, level)

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, slog.Level) bool); ok {
		r0 = returnFunc(context1, level)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSlogHandler_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockSlogHandler_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
//   - context1 context.Context
//   - level slog.Level
func (_e *MockSlogHandler_Expecter) Enabled(context1 interface{}, level interface{}) *MockSlogHandler_Enabled_Call {
	return &MockSlogHandler_Enabled_Call{Call: _e.mock.On("Enabled", context1, level)}
}

func (_c *MockSlogHandler_Enabled_Call) Run(run func(context1 context.Context, level slog.Level)) *MockSlogHandler_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 slog.Level
		if args[1] != nil {
			arg1 = args[1].(slog.Level)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSlogHandler_Enabled_Call) Return(b bool) *MockSlogHandler_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSlogHandler_Enabled_Call) RunAndReturn(run func(context1 context.Context, level slog.Level) bool) *MockSlogHandler_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type MockSlogHandler
func (_mock *MockSlogHandler) Handle(context1 context.Context, record slog.Record) error {
	ret := _mock.Called(context1, record)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, slog.Record) error); ok {
		r0 = returnFunc(context1, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSlogHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockSlogHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - context1 context.Context
//   - record slog.Record
func (_e *MockSlogHandler_Expecter) Handle(context1 interface{}, record interface{}) *MockSlogHandler_Handle_Call {
	return &MockSlogHandler_Handle_Call{Call: _e.mock.On("Handle", context1, record)}
}

func (_c *MockSlogHandler_Handle_Call) Run(run func(context1 context.Context, record slog.Record)) *MockSlogHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 slog.Record
		if args[1] != nil {
			arg1 = args[1].(slog.Record)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSlogHandler_Handle_Call) Return(err error) *MockSlogHandler_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSlogHandler_Handle_Call) RunAndReturn(run func(context1 context.Context, record slog.Record) error) *MockSlogHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// WithAttrs provides a mock function for the type MockSlogHandler
func (_mock *MockSlogHandler) WithAttrs(attrs []slog.Attr) slog.Handler {
	ret := _mock.Called(attrs)

	if len(ret) == 0 {
		panic("no return value specified for WithAttrs")
	}

	var r0 slog.Handler
	if returnFunc, ok := ret.Get(0).(func([]slog.Attr) slog.Handler); ok {
		r0 = returnFunc(attrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slog.Handler)
		}
	}
	return r0
}

// MockSlogHandler_WithAttrs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithAttrs'
type MockSlogHandler_WithAttrs_Call struct {
	*mock.Call
}

// WithAttrs is a helper method to define mock.On call
//   - attrs []slog.Attr
func (_e *MockSlogHandler_Expecter) WithAttrs(attrs interface{}) *MockSlogHandler_WithAttrs_Call {
	return &MockSlogHandler_WithAttrs_Call{Call: _e.mock.On("WithAttrs", attrs)}
}

func (_c *MockSlogHandler_WithAttrs_Call) Run(run func(attrs []slog.Attr)) *MockSlogHandler_WithAttrs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []slog.Attr
		if args[0] != nil {
			arg0 = args[0].([]slog.Attr)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSlogHandler_WithAttrs_Call) Return(handler slog.Handler) *MockSlogHandler_WithAttrs_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockSlogHandler_WithAttrs_Call) RunAndReturn(run func(attrs []slog.Attr) slog.Handler) *MockSlogHandler_WithAttrs_Call {
	_c.Call.Return(run)
	return _c
}

// WithGroup provides a mock function for the type MockSlogHandler
func (_mock *MockSlogHandler) WithGroup(name string) slog.Handler {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for WithGroup")
	}

	var r0 slog.Handler
	if returnFunc, ok := ret.Get(0).(func(string) slog.Handler); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slog.Handler)
		}
	}
	return r0
}

// MockSlogHandler_WithGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithGroup'
type MockSlogHandler_WithGroup_Call struct {
	*mock.Call
}

// WithGroup is a helper method to define mock.On call
//   - name string
func (_e *MockSlogHandler_Expecter) WithGroup(name interface{}) *MockSlogHandler_WithGroup_Call {
	return &MockSlogHandler_WithGroup_Call{Call: _e.mock.On("WithGroup", name)}
}

func (_c *MockSlogHandler_WithGroup_Call) Run(run func(name string)) *MockSlogHandler_WithGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSlogHandler_WithGroup_Call) Return(handler slog.Handler) *MockSlogHandler_WithGroup_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockSlogHandler_WithGroup_Call) RunAndReturn(run func(name string) slog.Handler) *MockSlogHandler_WithGroup_Call {
	_c.Call.Return(run)
	return _c
}
