// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package app

import (
	"context"

	"github.com/gemyago/golang-backend-boilerplate/internal/infrastructure/petstore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPetstoreClient creates a new instance of MockPetstoreClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetstoreClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetstoreClient {
	mock := &MockPetstoreClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPetstoreClient is an autogenerated mock type for the PetstoreClient type
type MockPetstoreClient struct {
	mock.Mock
}

type MockPetstoreClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetstoreClient) EXPECT() *MockPetstoreClient_Expecter {
	return &MockPetstoreClient_Expecter{mock: &_m.Mock}
}

// AddPet provides a mock function for the type MockPetstoreClient
func (_mock *MockPetstoreClient) AddPet(ctx context.Context, params petstore.AddPetParams) (*petstore.Pet, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for AddPet")
	}

	var r0 *petstore.Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, petstore.AddPetParams) (*petstore.Pet, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, petstore.AddPetParams) *petstore.Pet); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*petstore.Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, petstore.AddPetParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetstoreClient_AddPet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPet'
type MockPetstoreClient_AddPet_Call struct {
	*mock.Call
}

// AddPet is a helper method to define mock.On call
//   - ctx context.Context
//   - params petstore.AddPetParams
func (_e *MockPetstoreClient_Expecter) AddPet(ctx interface{}, params interface{}) *MockPetstoreClient_AddPet_Call {
	return &MockPetstoreClient_AddPet_Call{Call: _e.mock.On("AddPet", ctx, params)}
}

func (_c *MockPetstoreClient_AddPet_Call) Run(run func(ctx context.Context, params petstore.AddPetParams)) *MockPetstoreClient_AddPet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 petstore.AddPetParams
		if args[1] != nil {
			arg1 = args[1].(petstore.AddPetParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetstoreClient_AddPet_Call) Return(pet *petstore.Pet, err error) *MockPetstoreClient_AddPet_Call {
	_c.Call.Return(pet, err)
	return _c
}

func (_c *MockPetstoreClient_AddPet_Call) RunAndReturn(run func(ctx context.Context, params petstore.AddPetParams) (*petstore.Pet, error)) *MockPetstoreClient_AddPet_Call {
	_c.Call.Return(run)
	return _c
}

// GetPetByID provides a mock function for the type MockPetstoreClient
func (_mock *MockPetstoreClient) GetPetByID(ctx context.Context, params petstore.GetPetByIDParams) (*petstore.Pet, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPetByID")
	}

	var r0 *petstore.Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, petstore.GetPetByIDParams) (*petstore.Pet, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, petstore.GetPetByIDParams) *petstore.Pet); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*petstore.Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, petstore.GetPetByIDParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetstoreClient_GetPetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPetByID'
type MockPetstoreClient_GetPetByID_Call struct {
	*mock.Call
}

// GetPetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - params petstore.GetPetByIDParams
func (_e *MockPetstoreClient_Expecter) GetPetByID(ctx interface{}, params interface{}) *MockPetstoreClient_GetPetByID_Call {
	return &MockPetstoreClient_GetPetByID_Call{Call: _e.mock.On("GetPetByID", ctx, params)}
}

func (_c *MockPetstoreClient_GetPetByID_Call) Run(run func(ctx context.Context, params petstore.GetPetByIDParams)) *MockPetstoreClient_GetPetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 petstore.GetPetByIDParams
		if args[1] != nil {
			arg1 = args[1].(petstore.GetPetByIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetstoreClient_GetPetByID_Call) Return(pet *petstore.Pet, err error) *MockPetstoreClient_GetPetByID_Call {
	_c.Call.Return(pet, err)
	return _c
}

func (_c *MockPetstoreClient_GetPetByID_Call) RunAndReturn(run func(ctx context.Context, params petstore.GetPetByIDParams) (*petstore.Pet, error)) *MockPetstoreClient_GetPetByID_Call {
	_c.Call.Return(run)
	return _c
}
