// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package app

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPetsRepository creates a new instance of MockPetsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetsRepository {
	mock := &MockPetsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPetsRepository is an autogenerated mock type for the PetsRepository type
type MockPetsRepository struct {
	mock.Mock
}

type MockPetsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetsRepository) EXPECT() *MockPetsRepository_Expecter {
	return &MockPetsRepository_Expecter{mock: &_m.Mock}
}

// AddUserPet provides a mock function for the type MockPetsRepository
func (_mock *MockPetsRepository) AddUserPet(ctx context.Context, userPet UserPet) error {
	ret := _mock.Called(ctx, userPet)

	if len(ret) == 0 {
		panic("no return value specified for AddUserPet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UserPet) error); ok {
		r0 = returnFunc(ctx, userPet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPetsRepository_AddUserPet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserPet'
type MockPetsRepository_AddUserPet_Call struct {
	*mock.Call
}

// AddUserPet is a helper method to define mock.On call
//   - ctx context.Context
//   - userPet UserPet
func (_e *MockPetsRepository_Expecter) AddUserPet(ctx interface{}, userPet interface{}) *MockPetsRepository_AddUserPet_Call {
	return &MockPetsRepository_AddUserPet_Call{Call: _e.mock.On("AddUserPet", ctx, userPet)}
}

func (_c *MockPetsRepository_AddUserPet_Call) Run(run func(ctx context.Context, userPet UserPet)) *MockPetsRepository_AddUserPet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UserPet
		if args[1] != nil {
			arg1 = args[1].(UserPet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetsRepository_AddUserPet_Call) Return(err error) *MockPetsRepository_AddUserPet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPetsRepository_AddUserPet_Call) RunAndReturn(run func(ctx context.Context, userPet UserPet) error) *MockPetsRepository_AddUserPet_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPetIDs provides a mock function for the type MockPetsRepository
func (_mock *MockPetsRepository) GetUserPetIDs(ctx context.Context, userID string) ([]int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPetIDs")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetsRepository_GetUserPetIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPetIDs'
type MockPetsRepository_GetUserPetIDs_Call struct {
	*mock.Call
}

// GetUserPetIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPetsRepository_Expecter) GetUserPetIDs(ctx interface{}, userID interface{}) *MockPetsRepository_GetUserPetIDs_Call {
	return &MockPetsRepository_GetUserPetIDs_Call{Call: _e.mock.On("GetUserPetIDs", ctx, userID)}
}

func (_c *MockPetsRepository_GetUserPetIDs_Call) Run(run func(ctx context.Context, userID string)) *MockPetsRepository_GetUserPetIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetsRepository_GetUserPetIDs_Call) Return(int64s []int64, err error) *MockPetsRepository_GetUserPetIDs_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockPetsRepository_GetUserPetIDs_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]int64, error)) *MockPetsRepository_GetUserPetIDs_Call {
	_c.Call.Return(run)
	return _c
}

// HasUserPet provides a mock function for the type MockPetsRepository
func (_mock *MockPetsRepository) HasUserPet(ctx context.Context, userID string, petID int64) (bool, error) {
	ret := _mock.Called(ctx, userID, petID)

	if len(ret) == 0 {
		panic("no return value specified for HasUserPet")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (bool, error)); ok {
		return returnFunc(ctx, userID, petID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) bool); ok {
		r0 = returnFunc(ctx, userID, petID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, userID, petID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetsRepository_HasUserPet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUserPet'
type MockPetsRepository_HasUserPet_Call struct {
	*mock.Call
}

// HasUserPet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - petID int64
func (_e *MockPetsRepository_Expecter) HasUserPet(ctx interface{}, userID interface{}, petID interface{}) *MockPetsRepository_HasUserPet_Call {
	return &MockPetsRepository_HasUserPet_Call{Call: _e.mock.On("HasUserPet", ctx, userID, petID)}
}

func (_c *MockPetsRepository_HasUserPet_Call) Run(run func(ctx context.Context, userID string, petID int64)) *MockPetsRepository_HasUserPet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPetsRepository_HasUserPet_Call) Return(b bool, err error) *MockPetsRepository_HasUserPet_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPetsRepository_HasUserPet_Call) RunAndReturn(run func(ctx context.Context, userID string, petID int64) (bool, error)) *MockPetsRepository_HasUserPet_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserPet provides a mock function for the type MockPetsRepository
func (_mock *MockPetsRepository) RemoveUserPet(ctx context.Context, userID string, petID int64) error {
	ret := _mock.Called(ctx, userID, petID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserPet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, userID, petID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPetsRepository_RemoveUserPet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserPet'
type MockPetsRepository_RemoveUserPet_Call struct {
	*mock.Call
}

// RemoveUserPet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - petID int64
func (_e *MockPetsRepository_Expecter) RemoveUserPet(ctx interface{}, userID interface{}, petID interface{}) *MockPetsRepository_RemoveUserPet_Call {
	return &MockPetsRepository_RemoveUserPet_Call{Call: _e.mock.On("RemoveUserPet", ctx, userID, petID)}
}

func (_c *MockPetsRepository_RemoveUserPet_Call) Run(run func(ctx context.Context, userID string, petID int64)) *MockPetsRepository_RemoveUserPet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPetsRepository_RemoveUserPet_Call) Return(err error) *MockPetsRepository_RemoveUserPet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPetsRepository_RemoveUserPet_Call) RunAndReturn(run func(ctx context.Context, userID string, petID int64) error) *MockPetsRepository_RemoveUserPet_Call {
	_c.Call.Return(run)
	return _c
}
