// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// AddUserPetParams - Parameters for the addUserPet operation.
type AddUserPetParams struct { 
	UserID string `json:"userId"`
	Payload *AddPetRequest `json:"payload"`
}
