// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint
type AddPetRequestStatus string

// List of AddPetRequestStatus values.
const (
	AddPetRequestStatusAvailable AddPetRequestStatus = "available"
	AddPetRequestStatusPending AddPetRequestStatus = "pending"
	AddPetRequestStatusSold AddPetRequestStatus = "sold"
)

func(v AddPetRequestStatus) IsAvailable() bool {
  return v == AddPetRequestStatusAvailable
}

func(v AddPetRequestStatus) IsPending() bool {
  return v == AddPetRequestStatusPending
}

func(v AddPetRequestStatus) IsSold() bool {
  return v == AddPetRequestStatusSold
}

func(v AddPetRequestStatus) String() string {
	return string(v)
}

type assignableAddPetRequestStatus interface {
	IsAvailable() bool
	IsPending() bool
	IsSold() bool
	String() string
}

func AsAddPetRequestStatus(v assignableAddPetRequestStatus) (AddPetRequestStatus) {
	return AddPetRequestStatus(v.String())
}

func ParseAddPetRequestStatus(str string, target *AddPetRequestStatus) error {
	switch str {
	case "available":
		*target = AddPetRequestStatusAvailable
	case "pending":
		*target = AddPetRequestStatusPending
	case "sold":
		*target = AddPetRequestStatusSold
	default:
		return fmt.Errorf("unexpected AddPetRequestStatus value: %s", str)
	}
	return nil
}

func (v *AddPetRequestStatus) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	return ParseAddPetRequestStatus(str, v)
}

// All allowed values of AddPetRequestStatus enum.
var AllowableAddPetRequestStatusValues = []AddPetRequestStatus{
	AddPetRequestStatusAvailable,
	AddPetRequestStatusPending,
	AddPetRequestStatusSold,
}

type AddPetRequest struct { 
	Name string `json:"name"`
	Status AddPetRequestStatus `json:"status"`
	PhotoUrls []string `json:"photoUrls,omitempty"`
}
