// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type PetResponse struct { 
	ID int64 `json:"id"`
	Name string `json:"name"`
	Status string `json:"status"`
	PhotoUrls []string `json:"photoUrls,omitempty"`
}
