// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// RemoveUserPetParams - Parameters for the removeUserPet operation.
type RemoveUserPetParams struct { 
	UserID string `json:"userId"`
	PetID int64 `json:"petId"`
}
