// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// SendEchoParams - Parameters for the sendEcho operation.
type SendEchoParams struct { 
	Payload *EchoRequestPayload `json:"payload"`
}
