// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type UserResponse struct { 
	ID string `json:"id"`
	Name string `json:"name"`
	Email string `json:"email"`
}
