FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -tags=release -o /dist/server ./cmd/server

FROM gcr.io/distroless/static-debian12

COPY --from=builder /dist/server /server

EXPOSE 8080

ENTRYPOINT ["/server"]
CMD ["start", "--env", "production"]
