# Default configuration for the application, applies to all environments.

defaultLogLevel: INFO

pprofListener:
  # Make sure your app is fully internal if enabling it in production
  enabled: false
  addr: "localhost:6060"

# This should be aligned with actual runtime environment (e.g k8s or similar)
gracefulShutdownTimeout: 10s

httpServer:
  host: "[::]"
  port: 8080
  idleTimeout: 60s
  readHeaderTimeout: 2s
  readTimeout: 2s
  writeTimeout: 8s
  accessLogsLevel: ""

mcpServer:
  name: golang-backend-boilerplate-mcp
  version: 1.0.0
  httpHost: localhost
  httpPort: 8080

openTelemetry:
  # Enable or disable OpenTelemetry integration in one place
  enabled: false

  # Enable or disable collection of golang runtime metrics (CPU, memory, GC, etc.)
  # Uses https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/runtime
  runtimeMetrics: true

  # Traces configuration
  traces:
    enabled: false
    endpoint: ""
    urlPath: ""
    protocol: http/protobuf
    samplingRate: 1.0
    auth:
      token: ""
      tokenType: ""
  
  # Metrics configuration
  metrics:
    enabled: false
    endpoint: ""
    urlPath: ""
    protocol: http/protobuf
    exportInterval: 30s
    auth:
      token: ""
      tokenType: ""

  # Logs configuration
  logs:
    enabled: false

    # If true, logs will be sent to both default handler (e.g stdout) and OTEL handler
    # If false, logs will be sent only to OTEL handler
    defaultHandlerFanout: false
    
    endpoint: ""
    urlPath: ""
    protocol: http/protobuf
    auth:
      token: ""
      tokenType: ""

database:
  dsn: ./data/app.db

petstore:
  baseURL: https://petstore3.swagger.io/api/v3