// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewAddPetRequestValidator() FieldValidator[*AddPetRequest] {
	validateName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
		NewMinMaxLengthValidator[string, string](1, true),
	)
	validateStatus := NewSimpleFieldValidator[AddPetRequestStatus](
		EnsureNonDefault[AddPetRequestStatus],
	)
	validatePhotoUrls := NewArrayValidator[string](
		NewSimpleFieldValidator[[]string](
		),
		NewSimpleFieldValidator[string](
			),
	)
	
	return func(bindingCtx *BindingContext, value *AddPetRequest) {
		validateName(bindingCtx.Fork("name"), value.Name)
		validateStatus(bindingCtx.Fork("status"), value.Status)
		validatePhotoUrls(bindingCtx.Fork("photoUrls"), value.PhotoUrls)
	}
}
