// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewAddPetResponseValidator() FieldValidator[*AddPetResponse] {
	validatePetID := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	
	return func(bindingCtx *BindingContext, value *AddPetResponse) {
		validatePetID(bindingCtx.Fork("petId"), value.PetID)
	}
}
