// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewCreateUserResponseValidator() FieldValidator[*CreateUserResponse] {
	validateUserID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *CreateUserResponse) {
		validateUserID(bindingCtx.Fork("userId"), value.UserID)
	}
}
