// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewEchoRequestPayloadValidator() FieldValidator[*EchoRequestPayload] {
	validateMessage := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *EchoRequestPayload) {
		validateMessage(bindingCtx.Fork("message"), value.Message)
	}
}
