// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewHealthResponsePayloadValidator() FieldValidator[*HealthResponsePayload] {
	validateStatus := NewSimpleFieldValidator[HealthResponsePayloadStatus](
		EnsureNonDefault[HealthResponsePayloadStatus],
	)
	
	return func(bindingCtx *BindingContext, value *HealthResponsePayload) {
		validateStatus(bindingCtx.Fork("status"), value.Status)
	}
}
