// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewListUsersResponseValidator() FieldValidator[*ListUsersResponse] {
	validateUsers := NewArrayValidator[*UserResponse](
		NewSimpleFieldValidator[[]*UserResponse](
			EnsureArrayFieldRequired,
		),
		NewUserResponseValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *ListUsersResponse) {
		validateUsers(bindingCtx.Fork("users"), value.Users)
	}
}
