// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewListUserPetsResponseValidator() FieldValidator[*ListUserPetsResponse] {
	validatePets := NewArrayValidator[*PetResponse](
		NewSimpleFieldValidator[[]*PetResponse](
			EnsureArrayFieldRequired,
		),
		NewPetResponseValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *ListUserPetsResponse) {
		validatePets(bindingCtx.Fork("pets"), value.Pets)
	}
}
