// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewPetResponseValidator() FieldValidator[*PetResponse] {
	validateID := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateStatus := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validatePhotoUrls := NewArrayValidator[string](
		NewSimpleFieldValidator[[]string](
		),
		NewSimpleFieldValidator[string](
			),
	)
	
	return func(bindingCtx *BindingContext, value *PetResponse) {
		validateID(bindingCtx.Fork("id"), value.ID)
		validateName(bindingCtx.Fork("name"), value.Name)
		validateStatus(bindingCtx.Fork("status"), value.Status)
		validatePhotoUrls(bindingCtx.Fork("photoUrls"), value.PhotoUrls)
	}
}
