// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewUpdateUserRequestValidator() FieldValidator[*UpdateUserRequest] {
	validateName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
		NewMinMaxLengthValidator[string, string](1, true),
	)
	validateEmail := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *UpdateUserRequest) {
		validateName(bindingCtx.Fork("name"), value.Name)
		validateEmail(bindingCtx.Fork("email"), value.Email)
	}
}
