// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewUserResponseValidator() FieldValidator[*UserResponse] {
	validateID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateEmail := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *UserResponse) {
		validateID(bindingCtx.Fork("id"), value.ID)
		validateName(bindingCtx.Fork("name"), value.Name)
		validateEmail(bindingCtx.Fork("email"), value.Email)
	}
}
