// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports if that happens.
type _ func() EchoRequestPayload

type EchoController interface {
	// POST /echo
	//
	// Request type: SendEchoParams,
	//
	// Response type: EchoResponsePayload
	SendEcho(HandlerBuilder[
		*SendEchoParams,
		*EchoResponsePayload,
	]) http.Handler
}

// RegisterEchoRoutes will attach the following routes to the root handler:
// 
// - POST /echo
// 
// Routes will use provided controller to handle requests.
func(rootHandler *RootHandler) RegisterEchoRoutes(controller EchoController) *RootHandler {
	builder := newEchoControllerBuilder(rootHandler)
	rootHandler.router.HandleRoute("POST", "/echo", controller.SendEcho(builder.SendEcho))
	return rootHandler
}