// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/internal"
)

// Below is to workaround unused imports if that happens.
var _ = BindingContext{}
var _ = http.MethodGet
var _ = time.Time{}
type _ func() EchoRequestPayload

type paramsParserEchoSendEcho struct {
	bindPayload requestParamBinder[*http.Request, *EchoRequestPayload]
}

func (p *paramsParserEchoSendEcho) parse(router httpRouter, req *http.Request) (*SendEchoParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &SendEchoParams{}
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserEchoSendEcho(rootHandler *RootHandler) paramsParser[*SendEchoParams] {
	return &paramsParserEchoSendEcho{
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *EchoRequestPayload]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*EchoRequestPayload],
			),
			validateValue: NewEchoRequestPayloadValidator(),
		}),
	}
}

type echoControllerBuilder struct {
	// POST /echo
	//
	// Request type: SendEchoParams,
	//
	// Response type: EchoResponsePayload
	SendEcho genericHandlerBuilder[
		*SendEchoParams,
		*EchoResponsePayload,
		handlerActionFunc[*SendEchoParams, *EchoResponsePayload],
		httpHandlerActionFunc[*SendEchoParams, *EchoResponsePayload],
	]
}

func newEchoControllerBuilder(app *RootHandler) *echoControllerBuilder {
	return &echoControllerBuilder{
		// POST /echo
		SendEcho: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*SendEchoParams,
				*EchoResponsePayload,
			](),
			newHTTPHandlerAdapter[
				*SendEchoParams,
				*EchoResponsePayload,
			](),
			makeActionBuilderParams[
				*SendEchoParams,
				*EchoResponsePayload,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserEchoSendEcho(app),
			},
		),
	}
}
