// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports if that happens.
type _ func() Error

type HealthController interface {
	// GET /health
	//
	// Request type: none
	//
	// Response type: HealthResponsePayload
	HealthCheck(NoParamsHandlerBuilder[
		*HealthResponsePayload,
	]) http.Handler
}

// RegisterHealthRoutes will attach the following routes to the root handler:
// 
// - GET /health
// 
// Routes will use provided controller to handle requests.
func(rootHandler *RootHandler) RegisterHealthRoutes(controller HealthController) *RootHandler {
	builder := newHealthControllerBuilder(rootHandler)
	rootHandler.router.HandleRoute("GET", "/health", controller.HealthCheck(builder.HealthCheck))
	return rootHandler
}