// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports if that happens.
type _ func() AddPetRequest

type PetsController interface {
	// POST /users/{userId}/pets
	//
	// Request type: AddUserPetParams,
	//
	// Response type: AddPetResponse
	AddUserPet(HandlerBuilder[
		*AddUserPetParams,
		*AddPetResponse,
	]) http.Handler

	// GET /users/{userId}/pets
	//
	// Request type: ListUserPetsParams,
	//
	// Response type: ListUserPetsResponse
	ListUserPets(HandlerBuilder[
		*ListUserPetsParams,
		*ListUserPetsResponse,
	]) http.Handler

	// DELETE /users/{userId}/pets/{petId}
	//
	// Request type: RemoveUserPetParams,
	//
	// Response type: none
	RemoveUserPet(NoResponseHandlerBuilder[
		*RemoveUserPetParams,
	]) http.Handler
}

// RegisterPetsRoutes will attach the following routes to the root handler:
// 
// - POST /users/{userId}/pets
// 
// - GET /users/{userId}/pets
// 
// - DELETE /users/{userId}/pets/{petId}
// 
// Routes will use provided controller to handle requests.
func(rootHandler *RootHandler) RegisterPetsRoutes(controller PetsController) *RootHandler {
	builder := newPetsControllerBuilder(rootHandler)
	rootHandler.router.HandleRoute("POST", "/users/{userId}/pets", controller.AddUserPet(builder.AddUserPet))
	rootHandler.router.HandleRoute("GET", "/users/{userId}/pets", controller.ListUserPets(builder.ListUserPets))
	rootHandler.router.HandleRoute("DELETE", "/users/{userId}/pets/{petId}", controller.RemoveUserPet(builder.RemoveUserPet))
	return rootHandler
}