// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/internal"
)

// Below is to workaround unused imports if that happens.
var _ = BindingContext{}
var _ = http.MethodGet
var _ = time.Time{}
type _ func() AddPetRequest

type paramsParserPetsAddUserPet struct {
	bindUserID requestParamBinder[string, string]
	bindPayload requestParamBinder[*http.Request, *AddPetRequest]
}

func (p *paramsParserPetsAddUserPet) parse(router httpRouter, req *http.Request) (*AddUserPetParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &AddUserPetParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindUserID(pathParamsCtx.Fork("userId"), readPathValue("userId", router, req), &reqParams.UserID)
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserPetsAddUserPet(rootHandler *RootHandler) paramsParser[*AddUserPetParams] {
	return &paramsParserPetsAddUserPet{
		bindUserID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *AddPetRequest]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*AddPetRequest],
			),
			validateValue: NewAddPetRequestValidator(),
		}),
	}
}

type paramsParserPetsListUserPets struct {
	bindUserID requestParamBinder[string, string]
}

func (p *paramsParserPetsListUserPets) parse(router httpRouter, req *http.Request) (*ListUserPetsParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &ListUserPetsParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindUserID(pathParamsCtx.Fork("userId"), readPathValue("userId", router, req), &reqParams.UserID)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserPetsListUserPets(rootHandler *RootHandler) paramsParser[*ListUserPetsParams] {
	return &paramsParserPetsListUserPets{
		bindUserID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type paramsParserPetsRemoveUserPet struct {
	bindUserID requestParamBinder[string, string]
	bindPetID requestParamBinder[string, int64]
}

func (p *paramsParserPetsRemoveUserPet) parse(router httpRouter, req *http.Request) (*RemoveUserPetParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &RemoveUserPetParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindUserID(pathParamsCtx.Fork("userId"), readPathValue("userId", router, req), &reqParams.UserID)
	p.bindPetID(pathParamsCtx.Fork("petId"), readPathValue("petId", router, req), &reqParams.PetID)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserPetsRemoveUserPet(rootHandler *RootHandler) paramsParser[*RemoveUserPetParams] {
	return &paramsParserPetsRemoveUserPet{
		bindUserID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindPetID: newRequestParamBinder(binderParams[string, int64]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.int64Parser,
			),
			validateValue: NewSimpleFieldValidator[int64](
			),
		}),
	}
}

type petsControllerBuilder struct {
	// POST /users/{userId}/pets
	//
	// Request type: AddUserPetParams,
	//
	// Response type: AddPetResponse
	AddUserPet genericHandlerBuilder[
		*AddUserPetParams,
		*AddPetResponse,
		handlerActionFunc[*AddUserPetParams, *AddPetResponse],
		httpHandlerActionFunc[*AddUserPetParams, *AddPetResponse],
	]

	// GET /users/{userId}/pets
	//
	// Request type: ListUserPetsParams,
	//
	// Response type: ListUserPetsResponse
	ListUserPets genericHandlerBuilder[
		*ListUserPetsParams,
		*ListUserPetsResponse,
		handlerActionFunc[*ListUserPetsParams, *ListUserPetsResponse],
		httpHandlerActionFunc[*ListUserPetsParams, *ListUserPetsResponse],
	]

	// DELETE /users/{userId}/pets/{petId}
	//
	// Request type: RemoveUserPetParams,
	//
	// Response type: none
	RemoveUserPet genericHandlerBuilder[
		*RemoveUserPetParams,
		void,
		handlerActionFuncNoResponse[*RemoveUserPetParams, void],
		httpHandlerActionFuncNoResponse[*RemoveUserPetParams, void],
	]
}

func newPetsControllerBuilder(app *RootHandler) *petsControllerBuilder {
	return &petsControllerBuilder{
		// POST /users/{userId}/pets
		AddUserPet: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*AddUserPetParams,
				*AddPetResponse,
			](),
			newHTTPHandlerAdapter[
				*AddUserPetParams,
				*AddPetResponse,
			](),
			makeActionBuilderParams[
				*AddUserPetParams,
				*AddPetResponse,
			]{
				defaultStatus: 201,
				paramsParser:  newParamsParserPetsAddUserPet(app),
			},
		),

		// GET /users/{userId}/pets
		ListUserPets: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*ListUserPetsParams,
				*ListUserPetsResponse,
			](),
			newHTTPHandlerAdapter[
				*ListUserPetsParams,
				*ListUserPetsResponse,
			](),
			makeActionBuilderParams[
				*ListUserPetsParams,
				*ListUserPetsResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserPetsListUserPets(app),
			},
		),

		// DELETE /users/{userId}/pets/{petId}
		RemoveUserPet: newGenericHandlerBuilder(
			app,
			newHandlerAdapterNoResponse[
				*RemoveUserPetParams,
				void,
			](),
			newHTTPHandlerAdapterNoResponse[
				*RemoveUserPetParams,
				void,
			](),
			makeActionBuilderParams[
				*RemoveUserPetParams,
				void,
			]{
				defaultStatus: 204,
				voidResult:    true,
				paramsParser:  newParamsParserPetsRemoveUserPet(app),
			},
		),
	}
}
