// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/internal"
)

// Below is to workaround unused imports if that happens.
var _ = BindingContext{}
var _ = http.MethodGet
var _ = time.Time{}
type _ func() CreateUserRequest

type paramsParserUsersCreateUser struct {
	bindPayload requestParamBinder[*http.Request, *CreateUserRequest]
}

func (p *paramsParserUsersCreateUser) parse(router httpRouter, req *http.Request) (*CreateUserParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &CreateUserParams{}
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserUsersCreateUser(rootHandler *RootHandler) paramsParser[*CreateUserParams] {
	return &paramsParserUsersCreateUser{
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *CreateUserRequest]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*CreateUserRequest],
			),
			validateValue: NewCreateUserRequestValidator(),
		}),
	}
}

type paramsParserUsersDeleteUser struct {
	bindUserID requestParamBinder[string, string]
}

func (p *paramsParserUsersDeleteUser) parse(router httpRouter, req *http.Request) (*DeleteUserParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &DeleteUserParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindUserID(pathParamsCtx.Fork("userId"), readPathValue("userId", router, req), &reqParams.UserID)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserUsersDeleteUser(rootHandler *RootHandler) paramsParser[*DeleteUserParams] {
	return &paramsParserUsersDeleteUser{
		bindUserID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type paramsParserUsersGetUserByID struct {
	bindUserID requestParamBinder[string, string]
}

func (p *paramsParserUsersGetUserByID) parse(router httpRouter, req *http.Request) (*GetUserByIDParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &GetUserByIDParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindUserID(pathParamsCtx.Fork("userId"), readPathValue("userId", router, req), &reqParams.UserID)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserUsersGetUserByID(rootHandler *RootHandler) paramsParser[*GetUserByIDParams] {
	return &paramsParserUsersGetUserByID{
		bindUserID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type paramsParserUsersUpdateUser struct {
	bindUserID requestParamBinder[string, string]
	bindPayload requestParamBinder[*http.Request, *UpdateUserRequest]
}

func (p *paramsParserUsersUpdateUser) parse(router httpRouter, req *http.Request) (*UpdateUserParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &UpdateUserParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindUserID(pathParamsCtx.Fork("userId"), readPathValue("userId", router, req), &reqParams.UserID)
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserUsersUpdateUser(rootHandler *RootHandler) paramsParser[*UpdateUserParams] {
	return &paramsParserUsersUpdateUser{
		bindUserID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *UpdateUserRequest]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*UpdateUserRequest],
			),
			validateValue: NewUpdateUserRequestValidator(),
		}),
	}
}

type usersControllerBuilder struct {
	// POST /users
	//
	// Request type: CreateUserParams,
	//
	// Response type: CreateUserResponse
	CreateUser genericHandlerBuilder[
		*CreateUserParams,
		*CreateUserResponse,
		handlerActionFunc[*CreateUserParams, *CreateUserResponse],
		httpHandlerActionFunc[*CreateUserParams, *CreateUserResponse],
	]

	// DELETE /users/{userId}
	//
	// Request type: DeleteUserParams,
	//
	// Response type: none
	DeleteUser genericHandlerBuilder[
		*DeleteUserParams,
		void,
		handlerActionFuncNoResponse[*DeleteUserParams, void],
		httpHandlerActionFuncNoResponse[*DeleteUserParams, void],
	]

	// GET /users/{userId}
	//
	// Request type: GetUserByIDParams,
	//
	// Response type: UserResponse
	GetUserByID genericHandlerBuilder[
		*GetUserByIDParams,
		*UserResponse,
		handlerActionFunc[*GetUserByIDParams, *UserResponse],
		httpHandlerActionFunc[*GetUserByIDParams, *UserResponse],
	]

	// GET /users
	//
	// Request type: none
	//
	// Response type: ListUsersResponse
	ListUsers genericHandlerBuilder[
		void,
		*ListUsersResponse,
		handlerActionFuncNoParams[void, *ListUsersResponse],
		httpHandlerActionFuncNoParams[void, *ListUsersResponse],
	]

	// PUT /users/{userId}
	//
	// Request type: UpdateUserParams,
	//
	// Response type: none
	UpdateUser genericHandlerBuilder[
		*UpdateUserParams,
		void,
		handlerActionFuncNoResponse[*UpdateUserParams, void],
		httpHandlerActionFuncNoResponse[*UpdateUserParams, void],
	]
}

func newUsersControllerBuilder(app *RootHandler) *usersControllerBuilder {
	return &usersControllerBuilder{
		// POST /users
		CreateUser: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*CreateUserParams,
				*CreateUserResponse,
			](),
			newHTTPHandlerAdapter[
				*CreateUserParams,
				*CreateUserResponse,
			](),
			makeActionBuilderParams[
				*CreateUserParams,
				*CreateUserResponse,
			]{
				defaultStatus: 201,
				paramsParser:  newParamsParserUsersCreateUser(app),
			},
		),

		// DELETE /users/{userId}
		DeleteUser: newGenericHandlerBuilder(
			app,
			newHandlerAdapterNoResponse[
				*DeleteUserParams,
				void,
			](),
			newHTTPHandlerAdapterNoResponse[
				*DeleteUserParams,
				void,
			](),
			makeActionBuilderParams[
				*DeleteUserParams,
				void,
			]{
				defaultStatus: 204,
				voidResult:    true,
				paramsParser:  newParamsParserUsersDeleteUser(app),
			},
		),

		// GET /users/{userId}
		GetUserByID: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*GetUserByIDParams,
				*UserResponse,
			](),
			newHTTPHandlerAdapter[
				*GetUserByIDParams,
				*UserResponse,
			](),
			makeActionBuilderParams[
				*GetUserByIDParams,
				*UserResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserUsersGetUserByID(app),
			},
		),

		// GET /users
		ListUsers: newGenericHandlerBuilder(
			app,
			newHandlerAdapterNoParams[
				void,
				*ListUsersResponse,
			](),
			newHTTPHandlerAdapterNoParams[
				void,
				*ListUsersResponse,
			](),
			makeActionBuilderParams[
				void,
				*ListUsersResponse,
			]{
				defaultStatus: 200,
				paramsParser:  makeVoidParamsParser(app),
			},
		),

		// PUT /users/{userId}
		UpdateUser: newGenericHandlerBuilder(
			app,
			newHandlerAdapterNoResponse[
				*UpdateUserParams,
				void,
			](),
			newHTTPHandlerAdapterNoResponse[
				*UpdateUserParams,
				void,
			](),
			makeActionBuilderParams[
				*UpdateUserParams,
				void,
			]{
				defaultStatus: 204,
				voidResult:    true,
				paramsParser:  newParamsParserUsersUpdateUser(app),
			},
		),
	}
}
