// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports if that happens.
type _ func() CreateUserRequest

type UsersController interface {
	// POST /users
	//
	// Request type: CreateUserParams,
	//
	// Response type: CreateUserResponse
	CreateUser(HandlerBuilder[
		*CreateUserParams,
		*CreateUserResponse,
	]) http.Handler

	// DELETE /users/{userId}
	//
	// Request type: DeleteUserParams,
	//
	// Response type: none
	DeleteUser(NoResponseHandlerBuilder[
		*DeleteUserParams,
	]) http.Handler

	// GET /users/{userId}
	//
	// Request type: GetUserByIDParams,
	//
	// Response type: UserResponse
	GetUserByID(HandlerBuilder[
		*GetUserByIDParams,
		*UserResponse,
	]) http.Handler

	// GET /users
	//
	// Request type: none
	//
	// Response type: ListUsersResponse
	ListUsers(NoParamsHandlerBuilder[
		*ListUsersResponse,
	]) http.Handler

	// PUT /users/{userId}
	//
	// Request type: UpdateUserParams,
	//
	// Response type: none
	UpdateUser(NoResponseHandlerBuilder[
		*UpdateUserParams,
	]) http.Handler
}

// RegisterUsersRoutes will attach the following routes to the root handler:
// 
// - POST /users
// 
// - DELETE /users/{userId}
// 
// - GET /users/{userId}
// 
// - GET /users
// 
// - PUT /users/{userId}
// 
// Routes will use provided controller to handle requests.
func(rootHandler *RootHandler) RegisterUsersRoutes(controller UsersController) *RootHandler {
	builder := newUsersControllerBuilder(rootHandler)
	rootHandler.router.HandleRoute("POST", "/users", controller.CreateUser(builder.CreateUser))
	rootHandler.router.HandleRoute("DELETE", "/users/{userId}", controller.DeleteUser(builder.DeleteUser))
	rootHandler.router.HandleRoute("GET", "/users/{userId}", controller.GetUserByID(builder.GetUserByID))
	rootHandler.router.HandleRoute("GET", "/users", controller.ListUsers(builder.ListUsers))
	rootHandler.router.HandleRoute("PUT", "/users/{userId}", controller.UpdateUser(builder.UpdateUser))
	return rootHandler
}